services:
  rstudio:
    image: achubaty/landis-ii-v7
ports:
  - "127.0.0.1:8787:8585"
environment:
  - GROUPID: 1000
  - PASSWORD: Caribou4!
  - USERID: 1000
volumes:
  - ./.rstudio_config:/home/rstudio/.config/rstudio
  - ~/LANDIS-II/inputs:/home/rstudio/LANDIS-II/inputs
  - ~/LANDIS-II/outputs:/home/rstudio/LANDIS-II/outputs
#  - /mnt/scratch/achubaty/landis:/mnt/scratch
